import { z } from 'zod'

// Taxonomy categories for different entity types
export const TaxonomyCategorySchema = z.enum([
  // Item-related taxonomies
  'ItemType',
  'ItemRarity',
  'DamageType',
  'EquipmentSlot',
  'SpecialMaterial',
  'Currency',
  'WeaponType',
  'ArmorType',
  'ResistanceType',
  'ItemProperty',
  // Future: Can add NPC, Spell, Location taxonomies here
])

export type TaxonomyCategory = z.infer<typeof TaxonomyCategorySchema>

// Custom field definition for extensibility
export const TaxonomyCustomFieldSchema = z.object({
  name: z.string(),
  type: z.enum(['text', 'number', 'boolean', 'select', 'multiselect']),
  label: z.string(),
  required: z.boolean().default(false),
  options: z.array(z.string()).optional(), // For select/multiselect
  defaultValue: z.union([z.string(), z.number(), z.boolean()]).optional(),
})

export type TaxonomyCustomField = z.infer<typeof TaxonomyCustomFieldSchema>

// Main Taxonomy schema
export const TaxonomySchema = z.object({
  id: z.string().uuid(),
  category: TaxonomyCategorySchema,
  name: z.string().min(1),
  description: z.string().optional(),

  // Visual properties
  color: z.string().optional(), // Hex color or Tailwind color class
  icon: z.string().optional(), // Lucide icon name or emoji

  // System properties
  isSystem: z.boolean().default(false), // System taxonomies cannot be deleted
  sortOrder: z.number().default(0), // For custom ordering

  // Extensibility
  customFields: z.array(TaxonomyCustomFieldSchema).default([]),
  metadata: z.record(z.any()).default({}), // Additional flexible data

  // Meta
  createdAt: z.date(),
  updatedAt: z.date(),
})

export type Taxonomy = z.infer<typeof TaxonomySchema>

// Helper type for creating taxonomies without id and dates
export type TaxonomyInput = Omit<Taxonomy, 'id' | 'createdAt' | 'updatedAt'>

// Category display information
export const TAXONOMY_CATEGORIES: Record<
  TaxonomyCategory,
  {
    label: string
    pluralLabel: string
    description: string
    icon: string
  }
> = {
  ItemType: {
    label: 'Tipo de Objeto',
    pluralLabel: 'Tipos de Objeto',
    description: 'Categorías de objetos (armas, armaduras, pociones, etc.)',
    icon: 'Package',
  },
  ItemRarity: {
    label: 'Rareza',
    pluralLabel: 'Rarezas',
    description: 'Niveles de rareza de objetos',
    icon: 'Star',
  },
  DamageType: {
    label: 'Tipo de Daño',
    pluralLabel: 'Tipos de Daño',
    description: 'Tipos de daño para armas y hechizos',
    icon: 'Zap',
  },
  EquipmentSlot: {
    label: 'Ranura de Equipo',
    pluralLabel: 'Ranuras de Equipo',
    description: 'Posiciones de equipamiento en el personaje',
    icon: 'Grid',
  },
  SpecialMaterial: {
    label: 'Material Especial',
    pluralLabel: 'Materiales Especiales',
    description: 'Materiales especiales para objetos mágicos',
    icon: 'Gem',
  },
  Currency: {
    label: 'Moneda',
    pluralLabel: 'Monedas',
    description: 'Tipos de moneda del juego',
    icon: 'Coins',
  },
  WeaponType: {
    label: 'Tipo de Arma',
    pluralLabel: 'Tipos de Arma',
    description: 'Categorías de armas (simple, marcial, etc.)',
    icon: 'Sword',
  },
  ArmorType: {
    label: 'Tipo de Armadura',
    pluralLabel: 'Tipos de Armadura',
    description: 'Categorías de armadura (ligera, media, pesada)',
    icon: 'Shield',
  },
  ResistanceType: {
    label: 'Tipo de Resistencia',
    pluralLabel: 'Tipos de Resistencia',
    description: 'Tipos de resistencias e inmunidades',
    icon: 'ShieldCheck',
  },
  ItemProperty: {
    label: 'Propiedad de Objeto',
    pluralLabel: 'Propiedades de Objeto',
    description:
      'Propiedades especiales que pueden tener los objetos (almacenamiento, luz, etc.)',
    icon: 'Settings',
  },
}

// Default/seed taxonomies based on current hardcoded values
export const DEFAULT_TAXONOMIES: TaxonomyInput[] = [
  // Item Types
  {
    category: 'ItemType',
    name: 'Arma',
    isSystem: true,
    sortOrder: 1,
    icon: '⚔️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Armadura',
    isSystem: true,
    sortOrder: 2,
    icon: '🛡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Escudo',
    isSystem: true,
    sortOrder: 3,
    icon: '🛡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Objeto Mágico',
    isSystem: true,
    sortOrder: 4,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Poción',
    isSystem: true,
    sortOrder: 5,
    icon: '🧪',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Pergamino',
    isSystem: true,
    sortOrder: 6,
    icon: '📜',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Herramienta',
    isSystem: true,
    sortOrder: 7,
    icon: '🔧',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Equipo de Aventurero',
    isSystem: true,
    sortOrder: 8,
    icon: '🎒',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Tesoro',
    isSystem: true,
    sortOrder: 9,
    icon: '💎',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Varios',
    isSystem: true,
    sortOrder: 10,
    icon: '📦',
    customFields: [],
    metadata: {},
  },

  // Item Rarities
  {
    category: 'ItemRarity',
    name: 'Común',
    isSystem: true,
    sortOrder: 1,
    color: '#9CA3AF',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Poco Común',
    isSystem: true,
    sortOrder: 2,
    color: '#10B981',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Raro',
    isSystem: true,
    sortOrder: 3,
    color: '#3B82F6',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Muy Raro',
    isSystem: true,
    sortOrder: 4,
    color: '#8B5CF6',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Legendario',
    isSystem: true,
    sortOrder: 5,
    color: '#F59E0B',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Artefacto',
    isSystem: true,
    sortOrder: 6,
    color: '#EF4444',
    customFields: [],
    metadata: {},
  },

  // Damage Types
  {
    category: 'DamageType',
    name: 'Ácido',
    isSystem: true,
    sortOrder: 1,
    icon: '🧪',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Contundente',
    isSystem: true,
    sortOrder: 2,
    icon: '🔨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Cortante',
    isSystem: true,
    sortOrder: 3,
    icon: '🗡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Perforante',
    isSystem: true,
    sortOrder: 4,
    icon: '🏹',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Frío',
    isSystem: true,
    sortOrder: 5,
    icon: '❄️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Fuego',
    isSystem: true,
    sortOrder: 6,
    icon: '🔥',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Fuerza',
    isSystem: true,
    sortOrder: 7,
    icon: '💥',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Rayo',
    isSystem: true,
    sortOrder: 8,
    icon: '⚡',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Necrótico',
    isSystem: true,
    sortOrder: 9,
    icon: '💀',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Veneno',
    isSystem: true,
    sortOrder: 10,
    icon: '☠️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Psíquico',
    isSystem: true,
    sortOrder: 11,
    icon: '🧠',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Radiante',
    isSystem: true,
    sortOrder: 12,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Trueno',
    isSystem: true,
    sortOrder: 13,
    icon: '🌩️',
    customFields: [],
    metadata: {},
  },

  // Equipment Slots
  {
    category: 'EquipmentSlot',
    name: 'Cabeza',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Cuello',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Hombros',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Espalda',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Torso',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Muñecas',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Manos',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Cintura',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Piernas',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Pies',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Anillo',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Mano Principal',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Mano Secundaria',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Dos Manos',
    isSystem: true,
    sortOrder: 14,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Amuleto',
    isSystem: true,
    sortOrder: 15,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Ninguno',
    isSystem: true,
    sortOrder: 16,
    customFields: [],
    metadata: {},
  },

  // Special Materials
  {
    category: 'SpecialMaterial',
    name: 'Adamantina',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Mithral',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Plateada',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Madera Oscura',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Madera de Sangre',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Ninguno',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },

  // Currencies
  {
    category: 'Currency',
    name: 'Cobre',
    isSystem: true,
    sortOrder: 1,
    icon: '🟤',
    metadata: { abbreviation: 'cp', conversionRate: 1 },
  },
  {
    category: 'Currency',
    name: 'Plata',
    isSystem: true,
    sortOrder: 2,
    icon: '⚪',
    metadata: { abbreviation: 'sp', conversionRate: 10 },
  },
  {
    category: 'Currency',
    name: 'Electro',
    isSystem: true,
    sortOrder: 3,
    icon: '🟡',
    metadata: { abbreviation: 'ep', conversionRate: 50 },
  },
  {
    category: 'Currency',
    name: 'Oro',
    isSystem: true,
    sortOrder: 4,
    icon: '🟡',
    metadata: { abbreviation: 'gp', conversionRate: 100 },
  },
  {
    category: 'Currency',
    name: 'Platino',
    isSystem: true,
    sortOrder: 5,
    icon: '⚪',
    metadata: { abbreviation: 'pp', conversionRate: 1000 },
  },

  // Weapon Types
  {
    category: 'WeaponType',
    name: 'Arma Simple Cuerpo a Cuerpo',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Marcial Cuerpo a Cuerpo',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Simple a Distancia',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Marcial a Distancia',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },

  // Armor Types
  {
    category: 'ArmorType',
    name: 'Armadura Ligera',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ArmorType',
    name: 'Armadura Media',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ArmorType',
    name: 'Armadura Pesada',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },

  // Resistance Types (same as damage types)
  {
    category: 'ResistanceType',
    name: 'Ácido',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Contundente',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Cortante',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Perforante',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Frío',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Fuego',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Fuerza',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Rayo',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Necrótico',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Veneno',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Psíquico',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Radiante',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Trueno',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },

  // Item Properties
  {
    category: 'ItemProperty',
    name: 'Consumible',
    isSystem: true,
    sortOrder: 1,
    icon: '🍖',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Apilable',
    isSystem: true,
    sortOrder: 2,
    icon: '📚',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Tiene Almacenamiento',
    isSystem: true,
    sortOrder: 3,
    icon: '🎒',
    description: 'Este objeto puede contener otros objetos',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Emite Luz',
    isSystem: true,
    sortOrder: 4,
    icon: '💡',
    description: 'Este objeto emite luz',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Intercambiable',
    isSystem: true,
    sortOrder: 5,
    icon: '🤝',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Vinculado',
    isSystem: true,
    sortOrder: 6,
    icon: '🔒',
    description: 'Este objeto está vinculado a un personaje',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Mágico',
    isSystem: true,
    sortOrder: 7,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Maldito',
    isSystem: true,
    sortOrder: 8,
    icon: '💀',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Requiere Sintonización',
    isSystem: true,
    sortOrder: 9,
    icon: '🔮',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Identificado',
    isSystem: true,
    sortOrder: 10,
    icon: '🔍',
    customFields: [],
    metadata: {},
  },
]
