import { z } from 'zod'

// Taxonomy categories for different entity types
export const TaxonomyCategorySchema = z.enum([
  // Item-related taxonomies
  'ItemType',
  'ItemRarity',
  'DamageType',
  'EquipmentSlot',
  'SpecialMaterial',
  'Currency',
  'WeaponType',
  'ArmorType',
  'ResistanceType',
  'ItemProperty',
  // Song-related taxonomies
  'SongSchool',
  'InstrumentType',
  'MusicGenre',
  'SongComponent',
  'PerformanceQuality',
  'SongRange',
  'SongDuration',
  'SongProperty',
  // Future: Can add NPC, Location taxonomies here
])

export type TaxonomyCategory = z.infer<typeof TaxonomyCategorySchema>

// Custom field definition for extensibility
export const TaxonomyCustomFieldSchema = z.object({
  name: z.string(),
  type: z.enum(['text', 'number', 'boolean', 'select', 'multiselect']),
  label: z.string(),
  required: z.boolean().default(false),
  options: z.array(z.string()).optional(), // For select/multiselect
  defaultValue: z.union([z.string(), z.number(), z.boolean()]).optional(),
})

export type TaxonomyCustomField = z.infer<typeof TaxonomyCustomFieldSchema>

// Main Taxonomy schema
export const TaxonomySchema = z.object({
  id: z.string().uuid(),
  category: TaxonomyCategorySchema,
  name: z.string().min(1),
  description: z.string().optional(),

  // Visual properties
  color: z.string().optional(), // Hex color or Tailwind color class
  icon: z.string().optional(), // Lucide icon name or emoji

  // System properties
  isSystem: z.boolean().default(false), // System taxonomies cannot be deleted
  sortOrder: z.number().default(0), // For custom ordering

  // Extensibility
  customFields: z.array(TaxonomyCustomFieldSchema).default([]),
  metadata: z.record(z.string(), z.any()).default({}), // Additional flexible data

  // Meta
  createdAt: z.date(),
  updatedAt: z.date(),
})

export type Taxonomy = z.infer<typeof TaxonomySchema>

// Helper type for creating taxonomies without id and dates
export type TaxonomyInput = Omit<Taxonomy, 'id' | 'createdAt' | 'updatedAt'>

// Category display information
export const TAXONOMY_CATEGORIES: Record<
  TaxonomyCategory,
  {
    label: string
    pluralLabel: string
    description: string
    icon: string
  }
> = {
  ItemType: {
    label: 'Tipo de Objeto',
    pluralLabel: 'Tipos de Objeto',
    description: 'Categorías de objetos (armas, armaduras, pociones, etc.)',
    icon: 'Package',
  },
  ItemRarity: {
    label: 'Rareza',
    pluralLabel: 'Rarezas',
    description: 'Niveles de rareza de objetos',
    icon: 'Star',
  },
  DamageType: {
    label: 'Tipo de Daño',
    pluralLabel: 'Tipos de Daño',
    description: 'Tipos de daño para armas y hechizos',
    icon: 'Zap',
  },
  EquipmentSlot: {
    label: 'Ranura de Equipo',
    pluralLabel: 'Ranuras de Equipo',
    description: 'Posiciones de equipamiento en el personaje',
    icon: 'Grid',
  },
  SpecialMaterial: {
    label: 'Material Especial',
    pluralLabel: 'Materiales Especiales',
    description: 'Materiales especiales para objetos mágicos',
    icon: 'Gem',
  },
  Currency: {
    label: 'Moneda',
    pluralLabel: 'Monedas',
    description: 'Tipos de moneda del juego',
    icon: 'Coins',
  },
  WeaponType: {
    label: 'Tipo de Arma',
    pluralLabel: 'Tipos de Arma',
    description: 'Categorías de armas (simple, marcial, etc.)',
    icon: 'Sword',
  },
  ArmorType: {
    label: 'Tipo de Armadura',
    pluralLabel: 'Tipos de Armadura',
    description: 'Categorías de armadura (ligera, media, pesada)',
    icon: 'Shield',
  },
  ResistanceType: {
    label: 'Tipo de Resistencia',
    pluralLabel: 'Tipos de Resistencia',
    description: 'Tipos de resistencias e inmunidades',
    icon: 'ShieldCheck',
  },
  ItemProperty: {
    label: 'Propiedad de Objeto',
    pluralLabel: 'Propiedades de Objeto',
    description:
      'Propiedades especiales que pueden tener los objetos (almacenamiento, luz, etc.)',
    icon: 'Settings',
  },
  SongSchool: {
    label: 'Escuela de Canción',
    pluralLabel: 'Escuelas de Canción',
    description:
      'Escuelas de magia musical (Harmonía, Disonancia, Resonancia, Melodía, etc.)',
    icon: 'Music',
  },
  InstrumentType: {
    label: 'Tipo de Instrumento',
    pluralLabel: 'Tipos de Instrumento',
    description:
      'Categorías de instrumentos musicales (viento, cuerdas, percusión, teclas)',
    icon: 'Music2',
  },
  MusicGenre: {
    label: 'Género Musical',
    pluralLabel: 'Géneros Musicales',
    description:
      'Géneros musicales que afectan las propiedades de las canciones',
    icon: 'Radio',
  },
  SongComponent: {
    label: 'Componente de Canción',
    pluralLabel: 'Componentes de Canción',
    description:
      'Componentes requeridos para interpretar canciones (verbal, somático, etc.)',
    icon: 'ListChecks',
  },
  PerformanceQuality: {
    label: 'Calidad de Interpretación',
    pluralLabel: 'Calidades de Interpretación',
    description: 'Niveles de calidad de interpretación musical',
    icon: 'Trophy',
  },
  SongRange: {
    label: 'Alcance de Canción',
    pluralLabel: 'Alcances de Canción',
    description: 'Rangos de alcance para las canciones',
    icon: 'Target',
  },
  SongDuration: {
    label: 'Duración de Canción',
    pluralLabel: 'Duraciones de Canción',
    description: 'Duraciones posibles para las canciones',
    icon: 'Clock',
  },
  SongProperty: {
    label: 'Propiedad de Canción',
    pluralLabel: 'Propiedades de Canción',
    description: 'Propiedades especiales que pueden tener las canciones',
    icon: 'Sparkles',
  },
}

// Default/seed taxonomies based on current hardcoded values
export const DEFAULT_TAXONOMIES: TaxonomyInput[] = [
  // Item Types
  {
    category: 'ItemType',
    name: 'Arma',
    isSystem: true,
    sortOrder: 1,
    icon: '⚔️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Armadura',
    isSystem: true,
    sortOrder: 2,
    icon: '🛡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Escudo',
    isSystem: true,
    sortOrder: 3,
    icon: '🛡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Objeto Mágico',
    isSystem: true,
    sortOrder: 4,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Poción',
    isSystem: true,
    sortOrder: 5,
    icon: '🧪',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Pergamino',
    isSystem: true,
    sortOrder: 6,
    icon: '📜',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Herramienta',
    isSystem: true,
    sortOrder: 7,
    icon: '🔧',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Equipo de Aventurero',
    isSystem: true,
    sortOrder: 8,
    icon: '🎒',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Tesoro',
    isSystem: true,
    sortOrder: 9,
    icon: '💎',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemType',
    name: 'Varios',
    isSystem: true,
    sortOrder: 10,
    icon: '📦',
    customFields: [],
    metadata: {},
  },

  // Item Rarities
  {
    category: 'ItemRarity',
    name: 'Común',
    isSystem: true,
    sortOrder: 1,
    color: '#9CA3AF',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Poco Común',
    isSystem: true,
    sortOrder: 2,
    color: '#10B981',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Raro',
    isSystem: true,
    sortOrder: 3,
    color: '#3B82F6',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Muy Raro',
    isSystem: true,
    sortOrder: 4,
    color: '#8B5CF6',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Legendario',
    isSystem: true,
    sortOrder: 5,
    color: '#F59E0B',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemRarity',
    name: 'Artefacto',
    isSystem: true,
    sortOrder: 6,
    color: '#EF4444',
    customFields: [],
    metadata: {},
  },

  // Damage Types
  {
    category: 'DamageType',
    name: 'Ácido',
    isSystem: true,
    sortOrder: 1,
    icon: '🧪',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Contundente',
    isSystem: true,
    sortOrder: 2,
    icon: '🔨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Cortante',
    isSystem: true,
    sortOrder: 3,
    icon: '🗡️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Perforante',
    isSystem: true,
    sortOrder: 4,
    icon: '🏹',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Frío',
    isSystem: true,
    sortOrder: 5,
    icon: '❄️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Fuego',
    isSystem: true,
    sortOrder: 6,
    icon: '🔥',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Fuerza',
    isSystem: true,
    sortOrder: 7,
    icon: '💥',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Rayo',
    isSystem: true,
    sortOrder: 8,
    icon: '⚡',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Necrótico',
    isSystem: true,
    sortOrder: 9,
    icon: '💀',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Veneno',
    isSystem: true,
    sortOrder: 10,
    icon: '☠️',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Psíquico',
    isSystem: true,
    sortOrder: 11,
    icon: '🧠',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Radiante',
    isSystem: true,
    sortOrder: 12,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'DamageType',
    name: 'Trueno',
    isSystem: true,
    sortOrder: 13,
    icon: '🌩️',
    customFields: [],
    metadata: {},
  },

  // Equipment Slots
  {
    category: 'EquipmentSlot',
    name: 'Cabeza',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Cuello',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Hombros',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Espalda',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Torso',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Muñecas',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Manos',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Cintura',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Piernas',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Pies',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Anillo',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Mano Principal',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Mano Secundaria',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Dos Manos',
    isSystem: true,
    sortOrder: 14,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Amuleto',
    isSystem: true,
    sortOrder: 15,
    customFields: [],
    metadata: {},
  },
  {
    category: 'EquipmentSlot',
    name: 'Ninguno',
    isSystem: true,
    sortOrder: 16,
    customFields: [],
    metadata: {},
  },

  // Special Materials
  {
    category: 'SpecialMaterial',
    name: 'Adamantina',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Mithral',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Plateada',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Madera Oscura',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Madera de Sangre',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SpecialMaterial',
    name: 'Ninguno',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },

  // Currencies
  {
    category: 'Currency',
    name: 'Cobre',
    isSystem: true,
    sortOrder: 1,
    icon: '🟤',
    customFields: [],
    metadata: { abbreviation: 'cp', conversionRate: 1 },
  },
  {
    category: 'Currency',
    name: 'Plata',
    isSystem: true,
    sortOrder: 2,
    icon: '⚪',
    customFields: [],
    metadata: { abbreviation: 'sp', conversionRate: 10 },
  },
  {
    category: 'Currency',
    name: 'Electro',
    isSystem: true,
    sortOrder: 3,
    icon: '🟡',
    customFields: [],
    metadata: { abbreviation: 'ep', conversionRate: 50 },
  },
  {
    category: 'Currency',
    name: 'Oro',
    isSystem: true,
    sortOrder: 4,
    icon: '🟡',
    customFields: [],
    metadata: { abbreviation: 'gp', conversionRate: 100 },
  },
  {
    category: 'Currency',
    name: 'Platino',
    isSystem: true,
    sortOrder: 5,
    icon: '⚪',
    customFields: [],
    metadata: { abbreviation: 'pp', conversionRate: 1000 },
  },

  // Weapon Types
  {
    category: 'WeaponType',
    name: 'Arma Simple Cuerpo a Cuerpo',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Marcial Cuerpo a Cuerpo',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Simple a Distancia',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'WeaponType',
    name: 'Arma Marcial a Distancia',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },

  // Armor Types
  {
    category: 'ArmorType',
    name: 'Armadura Ligera',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ArmorType',
    name: 'Armadura Media',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ArmorType',
    name: 'Armadura Pesada',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },

  // Resistance Types (same as damage types)
  {
    category: 'ResistanceType',
    name: 'Ácido',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Contundente',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Cortante',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Perforante',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Frío',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Fuego',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Fuerza',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Rayo',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Necrótico',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Veneno',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Psíquico',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Radiante',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'ResistanceType',
    name: 'Trueno',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },

  // Item Properties
  {
    category: 'ItemProperty',
    name: 'Consumible',
    isSystem: true,
    sortOrder: 1,
    icon: '🍖',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Apilable',
    isSystem: true,
    sortOrder: 2,
    icon: '📚',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Tiene Almacenamiento',
    isSystem: true,
    sortOrder: 3,
    icon: '🎒',
    description: 'Este objeto puede contener otros objetos',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Emite Luz',
    isSystem: true,
    sortOrder: 4,
    icon: '💡',
    description: 'Este objeto emite luz',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Intercambiable',
    isSystem: true,
    sortOrder: 5,
    icon: '🤝',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Vinculado',
    isSystem: true,
    sortOrder: 6,
    icon: '🔒',
    description: 'Este objeto está vinculado a un personaje',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Mágico',
    isSystem: true,
    sortOrder: 7,
    icon: '✨',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Maldito',
    isSystem: true,
    sortOrder: 8,
    icon: '💀',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Requiere Sintonización',
    isSystem: true,
    sortOrder: 9,
    icon: '🔮',
    customFields: [],
    metadata: {},
  },
  {
    category: 'ItemProperty',
    name: 'Identificado',
    isSystem: true,
    sortOrder: 10,
    icon: '🔍',
    customFields: [],
    metadata: {},
  },

  // ========================================
  // SONG TAXONOMIES
  // ========================================

  // Song Schools
  {
    category: 'SongSchool',
    name: 'Abjuración',
    isSystem: true,
    sortOrder: 1,
    icon: '🛡️',
    description: 'Escuela de protección y barreras',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Conjuración',
    isSystem: true,
    sortOrder: 2,
    icon: '🌀',
    description: 'Escuela de invocación y creación',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Adivinación',
    isSystem: true,
    sortOrder: 3,
    icon: '🔮',
    description: 'Escuela de conocimiento y revelación',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Encantamiento',
    isSystem: true,
    sortOrder: 4,
    icon: '💫',
    description: 'Escuela de control mental y emociones',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Evocación',
    isSystem: true,
    sortOrder: 5,
    icon: '⚡',
    description: 'Escuela de energía y manifestación',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Ilusión',
    isSystem: true,
    sortOrder: 6,
    icon: '🎭',
    description: 'Escuela de engaño y apariencias',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Nigromancia',
    isSystem: true,
    sortOrder: 7,
    icon: '💀',
    description: 'Escuela de la muerte y no-muerte',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Transmutación',
    isSystem: true,
    sortOrder: 8,
    icon: '🔄',
    description: 'Escuela de transformación y cambio',
    customFields: [],
    metadata: { type: 'traditional' },
  },
  {
    category: 'SongSchool',
    name: 'Harmonía',
    isSystem: true,
    sortOrder: 9,
    icon: '🎵',
    color: '#10B981',
    description: 'Escuela de sanación, mejoras y cooperación',
    customFields: [],
    metadata: {
      type: 'musical',
      magicalAssociation: 'Sanación, mejoras, cooperación',
    },
  },
  {
    category: 'SongSchool',
    name: 'Disonancia',
    isSystem: true,
    sortOrder: 10,
    icon: '💥',
    color: '#EF4444',
    description: 'Escuela de debilitamiento, discordia y caos',
    customFields: [],
    metadata: {
      type: 'musical',
      magicalAssociation: 'Debilitamiento, discordia, caos',
    },
  },
  {
    category: 'SongSchool',
    name: 'Resonancia',
    isSystem: true,
    sortOrder: 11,
    icon: '🌊',
    color: '#3B82F6',
    description: 'Escuela de manipulación de materia y energía',
    customFields: [],
    metadata: {
      type: 'musical',
      magicalAssociation: 'Manipulación de materia y energía',
    },
  },
  {
    category: 'SongSchool',
    name: 'Melodía',
    isSystem: true,
    sortOrder: 12,
    icon: '💖',
    color: '#F59E0B',
    description: 'Escuela de encantamiento, emociones y efectos mentales',
    customFields: [],
    metadata: {
      type: 'musical',
      magicalAssociation: 'Encantamiento, emociones, efectos mentales',
    },
  },

  // Instrument Types
  {
    category: 'InstrumentType',
    name: 'Viento',
    isSystem: true,
    sortOrder: 1,
    icon: '🎺',
    description: 'Flautas, silbatos, cuernos',
    customFields: [],
    metadata: {
      magicalAssociation: 'Control del aire, comunicación, inspiración',
    },
  },
  {
    category: 'InstrumentType',
    name: 'Percusión',
    isSystem: true,
    sortOrder: 2,
    icon: '🥁',
    description: 'Tambores, campanas, carillones',
    customFields: [],
    metadata: {
      magicalAssociation: 'Ritmo vital, protección, invocación',
    },
  },
  {
    category: 'InstrumentType',
    name: 'Cuerdas',
    isSystem: true,
    sortOrder: 3,
    icon: '🎸',
    description: 'Guitarras, arpas, violines',
    customFields: [],
    metadata: {
      magicalAssociation: 'Emociones, encantamiento, sanación',
    },
  },
  {
    category: 'InstrumentType',
    name: 'Teclas',
    isSystem: true,
    sortOrder: 4,
    icon: '🎹',
    description: 'Pianos, órganos, clavicordios',
    customFields: [],
    metadata: {
      magicalAssociation: 'Armonía compleja, transformación, poder',
    },
  },

  // Music Genres
  {
    category: 'MusicGenre',
    name: 'Balada',
    isSystem: true,
    sortOrder: 1,
    icon: '🌸',
    color: '#10B981',
    description: 'Música suave y melódica',
    customFields: [],
    metadata: {
      effects: 'Sanación, paz, protección, emociones positivas',
    },
  },
  {
    category: 'MusicGenre',
    name: 'Marcha',
    isSystem: true,
    sortOrder: 2,
    icon: '⚔️',
    color: '#F59E0B',
    description: 'Ritmo fuerte y constante',
    customFields: [],
    metadata: {
      effects: 'Mejoras, movimiento, valor, liderazgo',
    },
  },
  {
    category: 'MusicGenre',
    name: 'Lamento',
    isSystem: true,
    sortOrder: 3,
    icon: '😢',
    color: '#6B7280',
    description: 'Música triste y melancólica',
    customFields: [],
    metadata: {
      effects: 'Debilitamiento, miedo, tristeza, maldiciones',
    },
  },
  {
    category: 'MusicGenre',
    name: 'Batalla',
    isSystem: true,
    sortOrder: 4,
    icon: '⚔️',
    color: '#EF4444',
    description: 'Música agresiva y poderosa',
    customFields: [],
    metadata: {
      effects: 'Combate, destrucción, furia, poder',
    },
  },
  {
    category: 'MusicGenre',
    name: 'Ritual',
    isSystem: true,
    sortOrder: 5,
    icon: '🔮',
    color: '#8B5CF6',
    description: 'Música ceremonial y mística',
    customFields: [],
    metadata: {
      effects: 'Invocación, transformación, adivinación, magia compleja',
    },
  },
  {
    category: 'MusicGenre',
    name: 'Popular',
    isSystem: true,
    sortOrder: 6,
    icon: '🎪',
    color: '#3B82F6',
    description: 'Música tradicional y sencilla',
    customFields: [],
    metadata: {
      effects: 'Utilidad cotidiana, efectos simples, comunidad',
    },
  },

  // Song Components
  {
    category: 'SongComponent',
    name: 'Verbal',
    isSystem: true,
    sortOrder: 1,
    icon: '💬',
    description: 'Requiere palabras o canto',
    customFields: [],
    metadata: { abbreviation: 'V' },
  },
  {
    category: 'SongComponent',
    name: 'Somático',
    isSystem: true,
    sortOrder: 2,
    icon: '🙌',
    description: 'Requiere gestos y movimientos',
    customFields: [],
    metadata: { abbreviation: 'S' },
  },
  {
    category: 'SongComponent',
    name: 'Material',
    isSystem: true,
    sortOrder: 3,
    icon: '💎',
    description: 'Requiere componentes materiales',
    customFields: [],
    metadata: { abbreviation: 'M' },
  },
  {
    category: 'SongComponent',
    name: 'Instrumental',
    isSystem: true,
    sortOrder: 4,
    icon: '🎵',
    description: 'Requiere un instrumento musical',
    customFields: [],
    metadata: { abbreviation: 'I' },
  },

  // Performance Quality
  {
    category: 'PerformanceQuality',
    name: 'Deficiente',
    isSystem: true,
    sortOrder: 1,
    icon: '📉',
    color: '#EF4444',
    description: 'Interpretación pobre (1-5)',
    customFields: [],
    metadata: {
      range: '1-5',
      effect: 'La canción puede fallar o tener efectos negativos',
    },
  },
  {
    category: 'PerformanceQuality',
    name: 'Adecuado',
    isSystem: true,
    sortOrder: 2,
    icon: '📊',
    color: '#F59E0B',
    description: 'Interpretación adecuada (6-10)',
    customFields: [],
    metadata: {
      range: '6-10',
      effect: 'Efecto básico de la canción',
    },
  },
  {
    category: 'PerformanceQuality',
    name: 'Bueno',
    isSystem: true,
    sortOrder: 3,
    icon: '📈',
    color: '#10B981',
    description: 'Interpretación buena (11-15)',
    customFields: [],
    metadata: {
      range: '11-15',
      effect: 'Efecto estándar de la canción',
    },
  },
  {
    category: 'PerformanceQuality',
    name: 'Excelente',
    isSystem: true,
    sortOrder: 4,
    icon: '⭐',
    color: '#3B82F6',
    description: 'Interpretación excelente (16-20)',
    customFields: [],
    metadata: {
      range: '16-20',
      effect: 'Efecto mejorado de la canción',
    },
  },
  {
    category: 'PerformanceQuality',
    name: 'Magistral',
    isSystem: true,
    sortOrder: 5,
    icon: '🌟',
    color: '#8B5CF6',
    description: 'Interpretación magistral (21+)',
    customFields: [],
    metadata: {
      range: '21+',
      effect: 'Efecto máximo con bonificaciones adicionales',
    },
  },

  // Song Ranges
  {
    category: 'SongRange',
    name: 'Toque',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: 'Personal',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '30 pies',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '60 pies',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '90 pies',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '120 pies',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '150 pies',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '300 pies',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '500 pies',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: '1 milla',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: 'Vista',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: 'Ilimitado',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongRange',
    name: 'Especial',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },

  // Song Durations
  {
    category: 'SongDuration',
    name: 'Instantáneo',
    isSystem: true,
    sortOrder: 1,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '1 acción',
    isSystem: true,
    sortOrder: 2,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '1 acción adicional',
    isSystem: true,
    sortOrder: 3,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '1 reacción',
    isSystem: true,
    sortOrder: 4,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '1 minuto',
    isSystem: true,
    sortOrder: 5,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '10 minutos',
    isSystem: true,
    sortOrder: 6,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '1 hora',
    isSystem: true,
    sortOrder: 7,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '8 horas',
    isSystem: true,
    sortOrder: 8,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: '24 horas',
    isSystem: true,
    sortOrder: 9,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Hasta ser disipado',
    isSystem: true,
    sortOrder: 10,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Concentración, hasta 1 minuto',
    isSystem: true,
    sortOrder: 11,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Concentración, hasta 10 minutos',
    isSystem: true,
    sortOrder: 12,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Concentración, hasta 1 hora',
    isSystem: true,
    sortOrder: 13,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Concentración, hasta 8 horas',
    isSystem: true,
    sortOrder: 14,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Concentración, hasta 24 horas',
    isSystem: true,
    sortOrder: 15,
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongDuration',
    name: 'Permanente',
    isSystem: true,
    sortOrder: 16,
    customFields: [],
    metadata: {},
  },

  // Song Properties
  {
    category: 'SongProperty',
    name: 'Ritual',
    isSystem: true,
    sortOrder: 1,
    icon: '🔮',
    description: 'Esta canción puede ser interpretada como ritual',
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongProperty',
    name: 'Concentración',
    isSystem: true,
    sortOrder: 2,
    icon: '🧘',
    description: 'Esta canción requiere concentración',
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongProperty',
    name: 'Requiere Competencia',
    isSystem: true,
    sortOrder: 3,
    icon: '🎓',
    description: 'Requiere competencia con el instrumento',
    customFields: [],
    metadata: {},
  },
  {
    category: 'SongProperty',
    name: 'Ensemble',
    isSystem: true,
    sortOrder: 4,
    icon: '👥',
    description: 'Requiere múltiples instrumentos',
    customFields: [],
    metadata: {},
  },
]
